# base image
image: Visual Studio 2019

environment:
  CCACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\.ccache"
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MINGW32

# set clone depth
clone_depth: 1 # clone entire repository history if not defined

cache:
  - .ccache

# version format
version: 1.3.16.{build}

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\autobuild\msys2\appveyor.bat'

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:
  - set
  - cmd: set SYNFIG_ID="%APPVEYOR_REPO_COMMIT_TIMESTAMP:~0,10%-win%MSYSTEM:-2%-%APPVEYOR_REPO_COMMIT:~0,5%"
  - cmd: call 7z a "SynfigStudio-1.3.16-testing-%SYNFIG_ID%.zip" %APPVEYOR_BUILD_FOLDER%\build\main.*

artifacts:
  - path: "SynfigStudio-1.3.16-testing-%SYNFIG_ID%.zip"

#deploy: off

deploy:
- provider: BinTray
  username: ice0
  api_key:
    secure: zMrTSvnYJ7yPiwkwsnvUeS/uo9L02e/jg9IKaJxOmBB/KugwyJ9o6WIF0vXHG3eq
  subject: ice0
  repo: lab
  package: lab-test
  version: testing
  publish: true
  override: true
  explode: false
