#include "examplewindow.h"
#include <gtkmm/application.h>
#include <iostream>

int main(int argc, char *argv[])
{
	auto app = Gtk::Application::create(argc, argv, "org.gtkmm.example");

	ExampleWindow window;
	Glib::RefPtr<Gtk::Builder> builder;
	app->signal_activate().connect([&app, &builder]() {
		//menbuar XML string
		Glib::ustring ui_info =
		"<interface>"
		"  <!-- menubar -->"
		"  <menu id='studio_menubar'>"

		//File menu
		"    <submenu>"
		"      <attribute name='label' translatable='yes'>_File</attribute>"
		"      <section>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_New</attribute>"
		"          <attribute name='action'>app.new</attribute>"
		"          <attribute name='accel'>&lt;Control&gt;n</attribute>"
		"        </item>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Open</attribute>"
		"          <attribute name='action'>app.open</attribute>"
		"          <attribute name='accel'>&lt;Control&gt;o</attribute>"
		"        </item>"

		//Open Recent submenu
		"	<submenu id='recent-file'>"
		"      <attribute name='label' translatable='yes'>_Open Recent</attribute>"
		"	</submenu>"

		//File menu cont
		"		</section>"
		"      <section>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Save</attribute>"
		"          <attribute name='action'>app.save</attribute>"
		"          <attribute name='accel'>&lt;Control&gt;s</attribute>"
		"        </item>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Save As...</attribute>"
		"          <attribute name='action'>app.save-as</attribute>"
		"          <attribute name='accel'>&lt;Control&gt;&lt;Shift&gt;s</attribute>"
		"        </item>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Save All...</attribute>"
		"          <attribute name='action'>app.save-all</attribute>"
		"          <attribute name='accel'>&lt;Control&gt;e</attribute>"
		"        </item>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Export...</attribute>"
		"          <attribute name='action'>app.export</attribute>"
		"        </item>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Revert...</attribute>"
		"          <attribute name='action'>app.revert</attribute>"
		"          <attribute name='icon'>document-revert</attribute>"
		"        </item>"
		"      </section>"
		"      <section>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Import...</attribute>"
		"          <attribute name='action'>app.import</attribute>"
		"          <attribute name='accel'>&lt;Control&gt;i</attribute>"
		"        </item>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Import Sequence...</attribute>"
		"          <attribute name='action'>app.import-sequence</attribute>"
		"        </item>"
		"      </section>"
		"      <section>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Preview...</attribute>"
		"          <attribute name='action'>app.preview</attribute>"
		"          <attribute name='accel'>F11</attribute>"
		"        </item>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Render...</attribute>"
		"          <attribute name='action'>app.render</attribute>"
		"          <attribute name='accel'>F9</attribute>"
		"        </item>"
		"      </section>"
		"		<section>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Close Document</attribute>"
		"				<attribute name='action'>app.close-document</attribute>"
		"          		<attribute name='accel'>&lt;Primary&gt;w</attribute>"
		"          		<attribute name='icon'>window-close</attribute>"
		"			</item>"
		"		</section>"
		"      <section>"
		"        <item>"
		"          <attribute name='label' translatable='yes'>_Quit</attribute>"
		"          <attribute name='action'>app.quit</attribute>"
		"          <attribute name='accel'>&lt;Primary&gt;q</attribute>"
		"          <attribute name='icon'>application-exit</attribute>"
		"        </item>"
		"      </section>"
		"    </submenu>"

		//Edit menu
		"	<submenu>"
		"		<attribute name='label' translatable='yes'>_Edit</attribute>"
		"		<section>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Undo</attribute>"
		"				<attribute name='action'>app.undo</attribute>"
		"				<attribute name='accel'>&lt;Primary&gt;z</attribute>"
		"				<attribute name='sensitive'>True</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Redo</attribute>"
		"				<attribute name='action'>app.redo</attribute>"
		"				<attribute name='accel'>&lt;Shift&gt;&lt;Primary&gt;z</attribute>"
		"			</item>"
		"		</section>"
		"		<section>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Cut</attribute>"
		"				<attribute name='action'>app.cut</attribute>"
		"				<attribute name='accel'>&lt;Primary&gt;x</attribute>"
		"				<attribute name='icon'>edit-cut</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Copy</attribute>"
		"				<attribute name='action'>app.copy</attribute>"
		"				<attribute name='accel'>&lt;Primary&gt;c</attribute>"
		"				<attribute name='icon'>edit-copy</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Paste</attribute>"
		"				<attribute name='action'>app.paste</attribute>"
		"				<attribute name='accel'>&lt;Primary&gt;v</attribute>"
		"				<attribute name='icon'>edit-paste</attribute>"
		"			</item>"
		"		</section>"
		"		<section>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Select All Layers</attribute>"
		"				<attribute name='action'>app.select-all-layers</attribute>"
		"				<attribute name='accel'>&lt;Control&gt;&lt;Shift&gt;a</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Unselect All Layers</attribute>"
		"				<attribute name='action'>app.unselect-all-layers</attribute>"
		"				<attribute name='accel'>&lt;Control&gt;&lt;Shift&gt;d</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Select All Handles</attribute>"
		"				<attribute name='action'>app.select-all-ducks</attribute>"
		"				<attribute name='accel'>&lt;Control&gt;a</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Unselect All Handles</attribute>"
		"				<attribute name='action'>app.unselect-all-ducks</attribute>"
		"				<attribute name='accel'>&lt;Control&gt;d</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Select Parent Layer</attribute>"
		"				<attribute name='action'>app.select-parent-layer</attribute>"
		//TODO: need to find accellerator for up arrow with two lines through it
		"				<attribute name='accel'>&lt;Alt&gt;&lt;Mod1&gt;Page_Up</attribute>"
		"			</item>"
		"		</section>"
		"		<section>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Input Devices...</attribute>"
		"				<attribute name='action'>app.input-devices</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Preferences...</attribute>"
		"				<attribute name='action'>app.setup</attribute>"
		"			</item>"
		"		</section>"
		"	</submenu>"

		//View submenu
		"	<submenu>"
		"		<attribute name='label' translatable='yes'>_View</attribute>"
		"		<section>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Show Menubar</attribute>"
		"				<attribute name='action'>app.show-menubar</attribute>"
		"			</item>"
		"			<item>"
		"				<attribute name='label' translatable='yes'>_Toolbar</attribute>"
		"				<attribute name='action'>app.show-toolbar</attribute>"
		"			</item>"
		"		</section>"
		"		<section>"
		//Show/Hide Handles submenu
		"			<submenu>"
		"				<attribute name='label' translatable='yes'>_Show/Hide Handles</attribute>"
		"					<item>"
		"						<attribute name='label' translatable='yes'>_Toggle None/Last visible Handles</attribute>"
		"						<attribute name='action'>app.mask-none-ducks</attribute>"
		"						<attribute name='accel'>&lt;Alt&gt;0</attribute>"
		"					</item>"
		"			</submenu>"
		"		</section>"
		"	</submenu>"
		"  </menu>"
		"</interface>";

		try {
			builder = Gtk::Builder::create_from_string(ui_info);
		} catch (const Glib::Error& ex) {
			std::cerr << "Building menus failed: " << ex.what();
		}
		auto menu_object = builder->get_object("studio_menubar");
		auto menu_bar = Glib::RefPtr<Gio::Menu>::cast_dynamic(menu_object);
		if ( !menu_bar ) {//|| !recent_menu) {
			g_warning("menu not found!");
		} else {
			app->set_menubar(menu_bar);
		}
	});

	//Shows the window and returns when it is closed.
	return app->run(window);
}