name: PR title linter

# update

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-and-lint-pr-title:
    runs-on: ubuntu-latest

    steps:
#      - name: Install gh-cli and npm and conventional commit linter
#        run: sudo apt install npm gh -y

#      - name: Install conventional commit linter
#        run: npm install --save-dev @commitlint/config-conventional @commitlint/cli

      - uses: actions/checkout@v3

      - name: Configure commitlint
        run: |
          echo 'module.exports = {extends: ['@commitlint/config-conventional']}' > commitlint.config.js

      - name: Lint current pull request title (test)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          gh pr view $pull_number --json=title --jq '.title' | npx commitlint

