# This is a basic workflow to help you get started with Actions

name: Synfig Studio (stable)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ v1.4.x ]
  pull_request:
    branches: [ v1.4.x ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Ubuntu (latest)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Dependencies (apt)
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
          HOMEBREW_NO_ANALYTICS: 1
        run: apt update && apt install cmake

      # Runs a set of commands using the runners shell
      - name: Build (CMake)
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          mkdir build && cd build && cmake ../cpp
